### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [MikeFot/Android--Location-Manager-Viewer#3]
Would you mind publishing the `.apk` file here on Github, for folks without Playstore access? Preferably on the `releases/` page (see [Creating Releases](https://help.github.com/articles/creating-releases/) in the Github help: It's as easy as pushing a tag and attaching the file to it). I'd love to include your app with [my F-Droid compatible Repo](https://android.izzysoft.de/repo) then and take care for updates, to allow easy maintenance for those people.

Thanks in advance!

**Comment by MikeFot** [comment]
Hello! 

Sorry for the late reply but I have been quite busy. Thank you for the suggestion! You can find version 1.1 in the releases page. I will try to do this for my other apps as well.

Thank you,

Michael

**Comment by IzzySoft** [comment]
Thanks Michael! And no worries: I know what it means to be "quite busy" (catches me too regularly). As promised, find [your app here now](https://apt.izzysoft.de/fdroid/index/apk/com.michaelfotiadis.locationmanagerviewer). Updates should appear in the repo automatically within 24h of your publishing them, so feel free to recommend the repo to your Google-free users :) 

Checking your other apps now as well :smile_cat:
