### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [MikeFot/Android--Location-Manager-Viewer#4]
With no (visible) activity for more than 2 years, just being curious: are you still maintaining this app?

**Comment by MikeFot** [comment]
Thank you for your question. I will get around to updating it sometime in the future.

Do you have anything that you would like to be added to the app?

**Comment by IzzySoft** [comment]
I was mainly asking because of the [listing in my F-Droid repo](https://apt.izzysoft.de/fdroid/index/apk/com.michaelfotiadis.locationmanagerviewer), whether I need to add an "EOL" mark for the users. Glad to see you didn't abandon the app! If the Fabric dependency could be removed, I gladly assist in getting your app moved to the official repo if you wish.

**Comment by MikeFot** [comment]
I have deleted the Fabric tracking for this on the remote side, but I never got around to removing it from the client as well. Thanks for reminding me!

**Comment by IzzySoft** [comment]
When you did and tagged a new version, feel free to ping me. We could then see to move it over to the official repo.

<sup>Note that I'll be AFK for about 2 weeks starting in a few days, so my response might be delayed then.</sup>
